"""phase5 books and publish records

Revision ID: 6915993508b2
Revises: 9eef2ff220cc
Create Date: 2026-05-28 00:52:51.806897
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6915993508b2'
down_revision: str | None = '9eef2ff220cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_records',
    sa.Column('book_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_records_book_id'), 'publish_records', ['book_id'], unique=False)
    op.create_index(op.f('ix_publish_records_chapter_id'), 'publish_records', ['chapter_id'], unique=False)
    op.add_column('books', sa.Column('topic', sa.String(length=2048), nullable=True))
    op.add_column('books', sa.Column('status', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'status')
    op.drop_column('books', 'topic')
    op.drop_index(op.f('ix_publish_records_chapter_id'), table_name='publish_records')
    op.drop_index(op.f('ix_publish_records_book_id'), table_name='publish_records')
    op.drop_table('publish_records')
    # ### end Alembic commands ###
